name: quizjets
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^0.22.0
  font_awesome_flutter: ^9.1.0
  url_launcher: 
  get_it:
  provider: ^5.0.0
  flutter_spinkit: ^5.0.0
  responsive_builder: ^0.4.1
  #firebase
  firebase_core: 
  cloud_firestore: 
  firebase_auth_web: ^1.0.2
  firebase_auth: ^1.0.2
  adaptive_theme: ^2.2.0
  image_picker: 
  path: ^1.8.0
  mime_type: ^1.0.0
  firebase_storage:
  file_picker: ^3.0.3
  mailer:
  #drop down
  dropdown_below: ^0.0.8
  cached_network_image: ^2.5.1
  percent_indicator:
  chewie: ^1.0.0
  video_player: ^2.1.1
  dio: 
  webview_flutter: ^1.0.0
  js: ^0.6.2
  url_strategy: ^0.2.0
  lottie: ^1.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/fonts/ 
    - assets/images/
    - assets/svgs/
     

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700